frame : test8::ErrorB::self (mut self : mut &(mut test8::ErrorB))-> void {
    {
        test8::Error::self(self)
    };
    {
        <unit-value>
    }
}
frame : test8::A::self (mut self : mut &(mut test8::A))-> void {
    {
        <unit-value>
    }
}
frame : test8::Error::self (mut self : mut &(mut test8::Error))-> void {
    {
        core::exception::Exception::self(self)
    };
    {
        <unit-value>
    }
}
frame : test8::B::foo (self : &(test8::B))-> void {
    throw test8::ErrorB::self(new);
    <unit-value>
}
frame : test8::B::self (mut self : mut &(mut test8::B))-> void {
    {
        test8::A::self(self)
    };
    {
        <unit-value>
    }
}
