fn foo ()
    throws AssertError
{
    let _ = {
        throw copy AssertError ("");
    };
}

fn main () {
    let _ = {
        return;
    };

    loop {
        let _ = {
            break 12;
        };
    }
}
