Error : when validating test8::main
 --> test_resources/control_flow/test8.yr:(3,4)
 3  ┃ fn main () {
    ╋    ^^^^
    ┃ Error : the pattern Ok(x : i32) with value test8::foo () is refutable
    ┃  --> test_resources/control_flow/test8.yr:(4,5)
    ┃  4  ┃     let Ok (x : i32) = foo (); // error, refutable since it may fail if /foo/ returns /none/
    ┃     ╋     ^^^
    ┃     ┗━━━━━━━    
    ┗━━━━━┻━ 
