Error : when validating test13::main
 --> test_resources/function/test13.yr:(4,4)
 4  ┃ fn main () {
    ╋    ^^^^
    ┃ Error : cannot create a function pointer from the unsafe function test13::foo ()-> void
    ┃  --> test_resources/function/test13.yr:(5,13)
    ┃  5  ┃     let a = &foo;
    ┃     ╋             ^
    ┃     ┗━━━━━━━
    ┃ Error : the call operator is not defined for a : error and {}
    ┃  --> test_resources/function/test13.yr:(6,7)
    ┃  6  ┃     a ();
    ┃     ╋       ^
    ┃     ┃ Error : defined here
    ┃     ┃  --> test_resources/function/test13.yr:(5,9)
    ┃     ┃  5  ┃     let a = &foo;
    ┃     ┃     ╋         ^
    ┃     ┃     ┃ Note : call operator is not defined for type error -- (test_resources/function/test13.yr:(6,7))
    ┃     ┃     ┗━━━━━━
    ┃     ┗━━━━━┻━
    ┗━━━━━┻━
