frame : test8::main ()-> void try {
    {
        test8::foo ();
        <unit-value>
    }
} finally {
    {
        try {
            {
                throw core::exception::AssertError::self(new, "Error"s8);
                <unit-value>
            }
        } catch {
            let #_catch : &(core::exception::AssertError)
            if ((true && true) && #{
                let _ : &(core::exception::AssertError) = #_catch;
                true
            #}) {
                {
                    test8::bar ();
                    <unit-value>
                }
            }
        };
        test8::baz ();
        <unit-value>
    }
}
