fn main ()
{
    {
    } exit {
        {
            throw copy AssertError ("Error");
        } catch {
            _ => { }
        }
    }
}
