fn main () {
    {

    } exit {
        {
            throw AssertError::new ("");
        } catch {
            _ => return ;
        }
    }
}
