frame : test6::main ()-> void {
    let _ : i32 = try {
            {
                test6::foo ()
            }
        } catch {
            let #_catch : &(core::exception::assertion::AssertError)
            if ((true && true) && #{
                let _ : &(core::exception::assertion::AssertError) = #_catch;
                true
            #}) {
                {
                    return {}
                }
            }
        };
    <unit-value>
}
