Error : when validating test8::main
 --> test_resources/aka/test8.yr:(19,4)
19  ┃ fn main () {
    ╋    ^^^^
    ┃ Error : {test8::inner::foo, test8::foo} called with {true} works with multiple candidates
    ┃  --> test_resources/aka/test8.yr:(21,17)
    ┃ 21  ┃     let _ = foo (true);
    ┃     ╋                 ^
    ┃     ┃ Note : candidate test8::foo (z : bool)-> i32 -- (test_resources/aka/test8.yr:(14,8))
    ┃     ┃ Note : candidate test8::inner::foo (x : bool)-> i32 -- (test_resources/aka/test8.yr:(4,12))
    ┃     ┗━━━━━━
    ┗━━━━━┻━
